services:
  php:
    build:
      context: .docker/php
    volumes:
      - ./jeedom/${JEEDOM_CORE_PATH}:/srv

  db:
    image: mariadb:${DB_VERSION:-10.6}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - database:/var/lib/mysql:rw

volumes:
  database:
